### ISSUE TITLE
4.3.21 and Edimax EW-7833UAC & D-Link DWA-192

### ISSUE THREAD

**Issue by heynnema** [diederikdehaas/rtl8814AU#1]
The 4.3.21 driver seems to work fine with the D-Link DWA-192 USB "globe on a wire" dongle.

The 4.3.21 driver kind of works with the Edimax EW-7833UAC USB dongle. http://us.edimax.com/edimax/merchandise/merchandise_detail/data/edimax/us/wireless_adapters_ac1750_dual-band/ew-7833uac/

If I connect using the 4.3.21 driver as is, it connects, but throws a lot of errors in syslog, and doesn't actually allow Internet access. Unless... if I restart Network Manager (Ubuntu 16.10), then it connects fine and allows Internet access, and the syslog is clean.

Some kind of initialization problem?

Al
heynnema at gmail dot com

**Comment by ulli-kroll** [comment]
@heynnema 

Can you confirm on which root HUB the DLINK DWA 192 connects.
EHCI or XHCI ??

**Comment by heynnema** [comment]
@ulli-kroll How can I tell?

**Comment by ulli-kroll** [comment]
They are different ways 

dmesg
```
[   18.011371] usb 2-2.1: new high-speed USB device number 3 using xhci_hcd
[   18.144369] usb 2-2.1: New USB device found, idVendor=0bda, idProduct=8813
[   18.151459] usb 2-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   18.159077] usb 2-2.1: Product: 802.11ac NIC
[   18.163488] usb 2-2.1: Manufacturer: Realtek
[   18.167911] usb 2-2.1: SerialNumber: 123456
```
high-speed -> EHCI on xhci_root hub

or busybox's lsusb I'm using with buildroot
```
buildroot ~ # lsusb | sort
Bus 002 Device 001: ID 1d6b:0002
Bus 002 Device 002: ID 05e3:0610
Bus 002 Device 003: ID 0bda:8813
Bus 002 Device 004: ID 05e3:0610
```
Note here 1d6b:0002 means Linux EHCI root hub

And with some magic you will see
```
[   18.488942] usb 3-2.1: new SuperSpeed USB device number 3 using xhci_hcd
[   18.520928] usb 3-2.1: Int endpoint with wBytesPerInterval of 512 in config 1 interface 0 altsetting 0 ep 133: setting to 64
[   18.534134] usb 3-2.1: New USB device found, idVendor=0bda, idProduct=8813
[   18.541228] usb 3-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   18.548723] usb 3-2.1: Product: 802.11ac NIC
[   18.553166] usb 3-2.1: Manufacturer: Realtek
[   18.557662] usb 3-2.1: SerialNumber: 123456

```
```
buildroot ~ # lsusb | sort
Bus 003 Device 001: ID 1d6b:0003
Bus 003 Device 002: ID 05e3:0612
Bus 003 Device 003: ID 05e3:0612
Bus 003 Device 004: ID 0bda:8813
```
here 1d6b:0003 means Linux XHCI root hub

0bda:8813 is some of my "test" devices ...

I'm wondering why no one found this magic ;-)

**Comment by heynnema** [comment]
dmesg looks like it says xhci. So what does that tell you, and why did you ask? Are you troubleshooting something, or trying to update the driver?

[165127.933096] usb 2-2: new high-speed USB device number 5 using xhci_hcd
[165128.077424] usb 2-2: New USB device found, idVendor=2001, idProduct=331a
[165128.077431] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[165128.077435] usb 2-2: Product: 11ac Adapter
[165128.077438] usb 2-2: Manufacturer: Realtek
[165128.077441] usb 2-2: SerialNumber: 123456
[165128.157638] RTL871X: module init start
[165128.157640] RTL871X: rtl8814au v4.3.21_17997.20160531
[165128.276631] RTL871X: rtw_ndev_init(wlan1) if1 mac_addr=e4:6f:13:29:f6:75
[165128.280140] usbcore: registered new interface driver rtl8814au
[165128.280143] RTL871X: module init ret=0
[165128.285231] rtl8814au 2-2:1.0 wlan4: renamed from wlan1
[165128.313771] IPv6: ADDRCONF(NETDEV_UP): wlan4: link is not ready
[165128.726292] IPv6: ADDRCONF(NETDEV_UP): wlan4: link is not ready
[165128.730465] IPv6: ADDRCONF(NETDEV_UP): wlan4: link is not ready
[165128.780297] IPv6: ADDRCONF(NETDEV_UP): wlan4: link is not ready
[165132.790410] RTL871X: nolinked power save enter
[165133.222259] RTL871X: nolinked power save leave

**Comment by ulli-kroll** [comment]
Hehe,
some of the pitfalls with Realtek devices that almost nobody detects
No USB 3.0 on default

note these line(s)
> [165127.933096] usb 2-2: new high-speed USB device number 5 using xhci_hcd
> [165128.077424] usb 2-2: New USB device found, idVendor=2001, idProduct=331a
> [165128.077431] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [165128.077435] usb 2-2: Product: 11ac Adapter
> [165128.077438] usb 2-2: Manufacturer: Realtek
> [165128.077441] usb 2-2: SerialNumber: 123456

high-speed on xhci_hcd -> USB 2.0

Compared with some magic in the driver
> [   18.488942] usb 3-2.1: new SuperSpeed USB device number 3 using xhci_hcd
> [   18.520928] usb 3-2.1: Int endpoint with wBytesPerInterval of 512 in config 1 interface 0 altsetting 0 ep 133: setting to 64
> [   18.534134] usb 3-2.1: New USB device found, idVendor=0bda, idProduct=8813
> [   18.541228] usb 3-2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [   18.548723] usb 3-2.1: Product: 802.11ac NIC
> [   18.553166] usb 3-2.1: Manufacturer: Realtek
> [   18.557662] usb 3-2.1: SerialNumber: 123456

SuperSpeed on xhci_hcd ->  USB3.0

Read here
https://github.com/ulli-kroll/rtl8814au
or here, with this driver I found the USB3 issue
https://github.com/ulli-kroll/rtl8821au

**Comment by ulli-kroll** [comment]
Try load the driver with

for use USB3.0
`insmod 8814au.ko rtw_switch_usb_mode=1`

and switch back to USB 2.0, or disconnect or cold reboot (power off)
`insmod 8814au.ko rtw_switch_usb_mode=2`

**Comment by heynnema** [comment]
If I understand what you're saying... is that the 8814au driver brings up the DWA-192 in usb2 mode, and then expects to be able to switch to usb3 mode, and that it is broken? And... that the rtw_switch_usb_mode param will force switch the usb ports to usb3 mode. If so, what does that do for usb2 ports on my computer, as I have both usb2 and usb3 ports. Also, could a file called, say, /etc/modprobe.d/8814au.conf, that contained "options 8814au rtw_switch_usb_mode=1" work?

**Comment by ulli-kroll** [comment]
No ...
The device itself starts with USB2, I've checked this with some USB3 thumb drive without usb storage support in the kernel. This is part of the negotiation.
Also with a true USB3 wifi device (mt7612u) this is the same, without any driver this will use USB3 if available.

There is some logic inside the device, which is checked by the driver, if this is connected to an USB3 root HUB *directly*. In this case the driver can switch to USB3,
It's absolutely safe to enable this switch in the driver.

It took about one week to figure out the stupid issue. And the release of the rtl8814au (after some time) revealed the missing parts to understand this.

**Comment by heynnema** [comment]
I think we just said the same thing, no?. The DWA-192 comes up in USB2 mode, and then the driver tries to switch it to USB3 (if it's directly connected to a USB3 port) mode. I'm not sure that I understand rtw_switch_usb_mode=1. Does this enable the driver to work this way, or does it force USB3 mode no matter? What did you think about my idea of an 8814au.conf?

**Comment by ulli-kroll** [comment]
No.
Please detach you from driver error, it's a device issue.
Normal USB3 devices will use Superspeed if they detect this, the logic of the device and NOT in the driver.
Realtek uses to switch this in the driver, which is WRONG in normal cases.

For 8814au.conf it's not needed and stupid, no driver should use userspace files.
Maybe I do this and other changes in my repository, including ripping the firmware blobs.

**Comment by diederikdehaas** [comment]
If you're still interested, you could try the new driver version I added to this repo (and made that into the default branch).
If it still doesn't work, then I can't help you. I don't have the knowledge to fix it and no desire to learn it. Sorry.
