### ISSUE TITLE
Asus USB-AC68 support

### ISSUE THREAD

**Issue by MarcosCC** [diederikdehaas/rtl8814AU#11]
Hi!

Any chance that the Asus USB-AC68 can be made to work with this driver? I have installed this (and a few other forks) but they can't ever connect (link up, my wireless shows, try to connect, then link goes down).

Happy to provide any logs and testing you may need, but I have no clue on C programming, much less drivers, sorry.

**Comment by asbroad** [comment]
Hi @MarcosCC, we ran into the same problem that you did and I think we solved it.  If you're still having the same problem, check out our pull request (https://github.com/diederikdehaas/rtl8814AU/pull/12).  The current driver does actually support the AC68 wireless usb device, however ASUS recently released a new version of the card that uses a different idProduct.

**Comment by diederikdehaas** [comment]
Please try the new driver version, I'm guessing it should work.
I'm closing the issue, but if it's still a problem, feel free to reopen it. Little warning: I don't intend to spend time on it, see the (new) README.
