### ISSUE TITLE
Cannot create multiple BSSs on one interface

### ISSUE THREAD

**Issue by andrejpodzimek** [diederikdehaas/rtl8814AU#17]
The creation of any additional BSSs in `hostapd` (using the `hostapd.conf` section after `bss=<new WiFi interface>` and `bssid=<new MAC address>`) fails. The driver probably doesn't support multiple BSSs on one interface, a feature very useful when configuring multiple WiFi networks with different authentications, routing rules etc. (This works OK on `ath10k` and `ath9k`.)

_Context: This is one of multiple bugs I'm filing based on my experiments with [this ArchLinux package](https://aur.archlinux.org/packages/rtl8814au-dkms-git/), [this device](https://www.amazon.com/dp/B01MZD7Z76/) and `hostapd` 2.6 on ArchLinux._

**Comment by ggerla** [comment]
Hi,
I need this feature. Do you think that it will be possible to implement it?

**Comment by diederikdehaas** [comment]
> Do you think that it will be possible to implement it?

I don't have the knowledge/skills to do that.
You should use this repo: https://github.com/aircrack-ng/rtl8814au
