### ISSUE TITLE
Cannot set VHT channel widths (80, 80+80, 160 MHz) on 5Ghz

### ISSUE THREAD

**Issue by andrejpodzimek** [diederikdehaas/rtl8814AU#19]
Setting ` vht_oper_chwidth=1` (to get 80 MHz channels) or any other VHT channel widths results in an odd error message:

```
Mode: IEEE 802.11a  Channel: 44  Frequency: 5220 MHz
DFS chan_idx seems wrong; num-ch: 37 ch-no: -6 conf-ch-no: 44 11n: 1 sec-ch: 1 vht-oper-width: 1
```

The same things hapens no matter what channel I select. (The entire output from `hostapd -d` is below.) It also happens with the high 5.7 GHz channels (e.g. 149, 153 etc.) The VHT wide channels are (indeed) not listed in Capabilities.

```
...
        Band 1:
                Capabilities: 0x19e3
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX HT20 SGI
                        RX HT40 SGI
                        TX STBC
                        RX STBC 1-stream
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
...
       Band 2:
                Capabilities: 0x19e3
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX HT20 SGI
                        RX HT40 SGI
                        TX STBC
                        RX STBC 1-stream
                        Max AMSDU length: 7935 bytes
                        DSSS/CCK HT40
...
```

My `hostapd.conf`:

```
interface=wlan1
bssid=02:c1:05:93:d8:b0
driver=nl80211
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=Extra Net3
country_code=CH
ieee80211d=0
ieee80211h=0
hw_mode=a
channel=44
acs_num_scans=10
beacon_int=100
dtim_period=1
rts_threshold=-1
fragm_threshold=-1
macaddr_acl=1
accept_mac_file=/etc/hostapd/hostapd.accept
auth_algs=1
ignore_broadcast_ssid=0
wmm_enabled=1
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_txop_limit=0
wmm_ac_be_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
ieee80211n=1
ht_capab=[LDPC][HT40-][HT40+][SHORT-GI-20][SHORT-GI-40][TX-STBC][TX-STBC1][DSSS_CCK-40]
require_ht=0
obss_interval=0
ieee80211ac=1
require_vht=0
vht_oper_chwidth=1
use_sta_nsts=1
ieee8021x=1
eapol_version=2
eapol_key_index_workaround=0
eap_server=1
eap_user_file=/etc/hostapd/hostapd.eap_user
ca_cert=/var/podzimek-ca/ca-cert.pem
server_cert=/etc/hostapd/hostapd.crt
private_key=/etc/hostapd/hostapd.key
check_crl=0
tls_session_lifetime=3600
wpa=2
wpa_key_mgmt=WPA-EAP
wpa_pairwise=CCMP
rsn_pairwise=CCMP
wpa_group_rekey=600
wpa_strict_rekey=1
wpa_gmk_rekey=86400
peerkey=1
ap_table_max_size=0
tdls_prohibit=0
tdls_prohibit_chan_switch=0
time_advertisement=2
time_zone=CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00
```

Output from `hostapd -d`:

```
random: Trying to read entropy from /dev/random
Configuration file: /etc/hostapd/hostapd.conf
ctrl_interface_group=0
eapol_version=2
nl80211: Supported cipher 00-0f-ac:1
nl80211: Supported cipher 00-0f-ac:5
nl80211: Supported cipher 00-0f-ac:2
nl80211: Supported cipher 00-0f-ac:4
nl80211: Supported vendor command: vendor_id=0x1018 subcmd=1
nl80211: Supported vendor command: vendor_id=0x1a11 subcmd=4106
nl80211: Supported vendor command: vendor_id=0x1a11 subcmd=4107
nl80211: Supported vendor event: vendor_id=0x1018 subcmd=0
nl80211: Supported vendor event: vendor_id=0x1018 subcmd=1
nl80211: interface wlan1 in phy phy7
nl80211: Set mode ifindex 18 iftype 3 (AP)
nl80211: Setup AP(wlan1) - device_ap_sme=1 use_monitor=0
nl80211: Subscribe to mgmt frames with AP handle 0x55f489aae3d0 (device SME)
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=04
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=0501
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=0504
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=06
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=08
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=09
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=0a
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=11
nl80211: Register frame type=0xd0 (WLAN_FC_STYPE_ACTION) nl_handle=0x55f489aae3d0 match=7f
nl80211: Enable Probe Request reporting nl_preq=0x55f489ab1980
nl80211: Register frame type=0x40 (WLAN_FC_STYPE_PROBE_REQ) nl_handle=0x55f489ab1980 match=
rfkill: initial event: idx=11 type=1 op=0 soft=0 hard=0
nl80211: Add own interface ifindex 18 (ifidx_reason -1)
nl80211: if_indices[16]: 18(-1)
phy: phy7
BSS count 1, BSSID mask 00:00:00:00:00:00 (0 bits)
wlan1: interface state UNINITIALIZED->COUNTRY_UPDATE
Previous country code CH, new country code CH 
nl80211: Regulatory information - country=CH (DFS-ETSI)
nl80211: 2402-2482 @ 40 MHz 20 mBm
nl80211: 5170-5250 @ 80 MHz 20 mBm
nl80211: 5250-5330 @ 80 MHz 20 mBm (DFS)
nl80211: 5490-5710 @ 160 MHz 27 mBm (DFS)
nl80211: 57000-66000 @ 2160 MHz 40 mBm
nl80211: Added 802.11b mode based on 802.11g information
Disable HT capability [DSSS_CCK-40] on 5 GHz band
hw vht capab: 0x0, conf vht capab: 0x0
wlan1: interface state COUNTRY_UPDATE->HT_SCAN
Scan for neighboring BSSes prior to enabling 40 MHz channel
40 MHz affected channel range: [5210,5250] MHz
wlan1: nl80211: scan request
nl80211: Passive scan requested
Scan requested (ret=0) - scan timeout 10 seconds
Interface initialization will be completed in a callback
ctrl_iface not configured!
random: Got 20/20 bytes from /dev/random
RTM_NEWLINK: ifi_index=18 ifname=wlan1 operstate=2 linkmode=0 ifi_family=0 ifi_flags=0x1002 ()
nl80211: Ignore interface down event since interface wlan1 is up
RTM_NEWLINK: ifi_index=18 ifname=wlan1 operstate=2 linkmode=0 ifi_family=0 ifi_flags=0x1003 ([UP])
nl80211: Drv Event 33 (NL80211_CMD_TRIGGER_SCAN) received for wlan1
wlan1: nl80211: Scan trigger
wlan1: Event SCAN_STARTED (47) received
Unknown event 47
RTM_NEWLINK: ifi_index=18 ifname=wlan1 wext ifi_family=0 ifi_flags=0x1003 ([UP])
nl80211: Drv Event 34 (NL80211_CMD_NEW_SCAN_RESULTS) received for wlan1
wlan1: nl80211: New scan results available
nl80211: Scan included frequencies: 5220 5240
wlan1: Event SCAN_RESULTS (3) received
nl80211: Received scan results (6 BSSes)
HT40: control channel: 44  secondary channel: 48
Completing interface initialization
Mode: IEEE 802.11a  Channel: 44  Frequency: 5220 MHz
DFS chan_idx seems wrong; num-ch: 37 ch-no: -6 conf-ch-no: 44 11n: 1 sec-ch: 1 vht-oper-width: 1
Available channel: 34
Available channel: 36
Available channel: 38
Available channel: 40
Available channel: 42
Available channel: 44
Available channel: 46
Available channel: 48
Available channel: 52
Available channel: 56
Available channel: 60
Available channel: 64
Available channel: 100
Available channel: 104
Available channel: 108
Available channel: 112
Available channel: 116
Available channel: 120
Available channel: 124
Available channel: 128
Available channel: 132
Available channel: 136
Available channel: 140
Available channel: 149
Available channel: 153
Available channel: 157
Available channel: 161
Available channel: 165
Available channel: 0
Available channel: 0
Available channel: 0
Available channel: 0
Available channel: 0
Available channel: 0
Available channel: 0
Available channel: 0
Available channel: 0
Interface initialization failed
wlan1: interface state HT_SCAN->DISABLED
wlan1: AP-DISABLED 
hostapd_interface_deinit_free(0x55f489aa6f90)
hostapd_interface_deinit_free: num_bss=1 conf->num_bss=1
hostapd_interface_deinit(0x55f489aa6f90)
wlan1: interface state DISABLED->DISABLED
hostapd_bss_deinit: deinit bss wlan1
wlan1: Deauthenticate all stations
nl80211: sta_remove -> DEL_STATION wlan1 ff:ff:ff:ff:ff:ff --> -22 (Invalid argument)
wlan1: AP-DISABLED 
hostapd_cleanup(hapd=0x55f489aab8e0 (wlan1))
hostapd_free_hapd_data: Interface wlan1 wasn't started
hostapd_interface_deinit_free: driver=0x55f48972bda0 drv_priv=0x55f489aa83c0 -> hapd_deinit
nl80211: deinit ifname=wlan1 disabled_11b_rates=0
nl80211: Disable Probe Request reporting nl_preq=0x8888dd7c01239109
nl80211: Remove monitor interface: refcount=0
nl80211: Remove beacon (ifindex=18)
netlink: Operstate: ifindex=18 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
nl80211: Set mode ifindex 18 iftype 2 (STATION)
nl80211: Teardown AP(wlan1) - device_ap_sme=1 use_monitor=0
nl80211: Unsubscribe mgmt frames handle 0x8888dd7c01226b59 (AP teardown (dev SME))
hostapd_interface_free(0x55f489aa6f90)
hostapd_interface_free: free hapd 0x55f489aab8e0
hostapd_cleanup_iface(0x55f489aa6f90)
hostapd_cleanup_iface_partial(0x55f489aa6f90)
hostapd_cleanup_iface: free iface=0x55f489aa6f90
```

_Context: This is one of multiple bugs I'm filing based on my experiments with [this ArchLinux package](https://aur.archlinux.org/packages/rtl8814au-dkms-git/), [this device](https://www.amazon.com/dp/B01MZD7Z76/) and `hostapd` 2.6 on ArchLinux._

**Comment by StuntsPT** [comment]
Sorry about the "necrobumping", but did you ever solve this issue?
I have the very same error and can't seem to get past it.
Thanks.

**Comment by andrejpodzimek** [comment]
Sadly, all I can say is that I haven't resolved any of [these issues](https://github.com/diederikdehaas/rtl8814AU/issues/created_by/andrejpodzimek). There has been some activity on [the AUR page](https://aur.archlinux.org/packages/rtl8814au-dkms-git/) and it looks like Realtek may have a new version of the source code somehow somewhere, but that's all I know.

For me the card works as a temporary solution to run a USB 3.0 access point. But once my regular home server with its `ath10k` cards gets back from ~vacation~ warranty repair, I'll probably stop using the Realtek, because it really can't do VHT too much. Surprisingly though, this Realtek does achieve much higher transfer rates than an old 802.11n-only `ath9k`. Not sure why that is. All in all it kind of works for me, but I'm just not getting any fancy 500+ Mb/s rates with it; it's mostly way below 200 Mb/s.

**Comment by StuntsPT** [comment]
Yeah, the thing is I'm getting this problem with an Atheros card... Specifically a QCA9882 chip which uses the `ath10k` driver.
And since I can't seem to activate the 80Mhz frequency, I can't even go above 56Mbps speeds in 5Ghz mode (which is quite ironic, since in 2.4Ghz mode, I can get up to 96Mbps speeds).
Anyway, thank you for your reply.

**Comment by nirmalpanchal** [comment]
As, I can see you are missing  'vht_oper_centr_freq_seg0_idx=' config in hostapd.conf. it should be calculated as (channel+6) in most cases.
when you assign channel width 80Mhz for 80211ac you need to assign center freq for channel.
also, make sure channel is available to use in your country
https://en.wikipedia.org/wiki/List_of_WLAN_channels

also, check if your hardware supports 80MHz channel width. If it is wave1 device, 80Mhz support is mandatory.
you can verify it by seeing output of 'iw dev phy phyX info' 
find lines
VHT Capabilities (0xxxxxxxx):
			Max MPDU length: 
			Supported Channel Width:

I am also using QCA9882 chipset and ath10k driver, and i can make 80Mhz working and achieve 866.7Mbps rate.

I hope this help !!

**Comment by StuntsPT** [comment]
Thank you for pitching in!
(And apologies to the OP for hijacking this thread)
I guess my card does not support 80Mhz. Here is the output of `iw phy phy0 info |grep -A 3`
```
VHT Capabilities (0x338001b2):
			Max MPDU length: 11454
			Supported Channel Width: neither 160 nor 80+80
```
Is this supposed to vary when using the same chip?

**Comment by nirmalpanchal** [comment]
> Thank you for pitching in!
> (And apologies to the OP for hijacking this thread)
> I guess my card does not support 80Mhz. Here is the output of `iw phy phy0 info |grep -A 3`
> 
> ```
> VHT Capabilities (0x338001b2):
> 			Max MPDU length: 11454
> 			Supported Channel Width: neither 160 nor 80+80
> ```
> 
> Is this supposed to vary when using the same chip?

No this does not mean your card does not support 80MHz. It means your card does not support 80+80 or 160MHz. I believe your card does support 80Mhz bandwidth.
can you share me detail of your wireless card ?
did you try putting 'vht_oper_centr_freq_seg0_idx=' config in your hostapd.conf file ?

Thanks

**Comment by StuntsPT** [comment]
Hi @nirmalpanchal, sorry it has taken so long for me to reply. I have somehow missed this notification, and now I took another stab at the problem and I found your post.
To answer your question, the card is a Sparklan WPEQ-257ACN, which is seen in `lspci` as:

```
02:00.0 Network controller: Qualcomm Atheros QCA986x/988x 802.11ac Wireless Network Adapter
```
The chip is actually a QCA9882.

It seems that my issue is related with the builtin EEPROM regdom. Somehow it is blocking every single 5GHz channel. In order to work around the issue, I need a [patched](https://github.com/openwrt/openwrt/blob/master/package/kernel/mac80211/patches/ath/402-ath_regd_optional.patch) kernel, but I am even having some trouble applying this patch to the Arch Linux kernel (since the OpenWRT kernel is heavily patched!).
If I ever make it to get 5Ghz working, I'll post back.

**Comment by LucaZeta** [comment]
Probably it will not help, but following is a quite well working hostapd.conf specifically used with a chipset like yours. 390Mbps with 80Mhz channel. I'm still in a big mess to get full 800Mbps.

interface=wlp4s0
bridge=br0
driver=nl80211
logger_syslog=-1
logger_syslog_level=2
logger_stdout=-1
logger_stdout_level=2
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
ssid=WiFi-300
country_code=IT
ieee80211d=1
ieee80211h=1
hw_mode=a
channel=acs_survey
beacon_int=100
dtim_period=2
max_num_sta=255
rts_threshold=-1
fragm_threshold=-1
macaddr_acl=0
auth_algs=3
ignore_broadcast_ssid=0
tx_queue_data3_aifs=7
tx_queue_data3_cwmin=15
tx_queue_data3_cwmax=1023
tx_queue_data3_burst=0
tx_queue_data2_aifs=3
tx_queue_data2_cwmin=15
tx_queue_data2_cwmax=63
tx_queue_data2_burst=0
tx_queue_data1_aifs=1
tx_queue_data1_cwmin=7
tx_queue_data1_cwmax=15
tx_queue_data1_burst=3.0
tx_queue_data0_aifs=1
tx_queue_data0_cwmin=3
tx_queue_data0_cwmax=7
tx_queue_data0_burst=1.5
wmm_enabled=1
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_aifs=3
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_txop_limit=0
wmm_ac_be_acm=0
wmm_ac_vi_aifs=2
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_aifs=2
wmm_ac_vo_cwmin=2
wmm_ac_vo_cwmax=3
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
ieee80211n=1
ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40]
ieee80211ac=1
vht_oper_chwidth=1
vht_oper_centr_freq_seg0_idx=42
eapol_key_index_workaround=0
eap_server=0
own_ip_addr=127.0.0.1
wpa=2
wpa_psk_file=/etc/hostapd/hostapd.wpa_psk
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP CCMP
rsn_pairwise=TKIP CCMP

**Comment by Aveline67** [comment]
> Probably it will not help, but following is a quite well working hostapd.conf specifically used with
> ...
> channel=acs_survey
> ...
> vht_oper_centr_freq_seg0_idx=42

No point to set seg0_idx if DFS is used. Also DFS with hostapd doesnt seem right for this time. Use channel=36 with seg0_idx= 42 and do no set ieee80211d and ieee80211dh.

**Comment by atzlinux** [comment]
I meet the same question.

Is need the firmware or kernel driver modules support the dfs at first?

**Comment by diederikdehaas** [comment]
I don't have the knowledge/skills to fix this. Try here instead: https://github.com/aircrack-ng/rtl8814au
