### ISSUE TITLE
MTU is limited to 1500 bytes

### ISSUE THREAD

**Issue by andrejpodzimek** [diederikdehaas/rtl8814AU#20]
WiFi cards can usually set MTUs between 2000&ndash;3000 bytes, but the 8814au driver limits this to 1500 bytes (the ethernet magic number). Some high-bandwidth `hostapd` access points could benefit from larger MTUs; both Intel and Qualcomm / Atheros can do it.

_Context: This is one of multiple bugs I'm filing based on my experiments with [this ArchLinux package](https://aur.archlinux.org/packages/rtl8814au-dkms-git/), [this device](https://www.amazon.com/dp/B01MZD7Z76/) and `hostapd` 2.6 on ArchLinux._

**Comment by diederikdehaas** [comment]
Like the other issues, try here instead: https://github.com/aircrack-ng/rtl8814au
