### ISSUE TITLE
New T9UH 4.3.21.1 driver base for rtl8814au

### ISSUE THREAD

**Issue by zebulon2** [diederikdehaas/rtl8814AU#22]
Hi, TP-Link has published a new driver for their T9UH https://www.tp-link.com/us/download/Archer-T9UH.html#Driver. It is labelled T9UH_linux_v4.3.21.1_24835.20171031. Would you like to pull the changes? Thanks in advance.

**Comment by traud** [comment]
Just for the records: Edimax posted the same driver version for their [EW-7833UAC…](https://www.edimax.com/edimax/download/download/data/edimax/global/download/product/wireless_adapters/wireless_adapters_ac1750_dual-band/ew-7833uac/)  
It is labelled rtl8814AU_linux_v4.3.21.1_2017**1108** but it is the same, except for one different device ID in `os_dep/linux/usb_intf.c`.

**Comment by diederikdehaas** [comment]
Thanks for that last link. I've downloaded the latest one I found there and added that to this repo.
