### ISSUE TITLE
Update for kernel 5.8

### ISSUE THREAD

**Issue by kamigari84** [diederikdehaas/rtl8814AU#23]
After the last kernel update I got, the driver (once again) fails to build (for - due to changes in kernel API/sorce, perhaps?
Could someone please have a look at it, please?

**Comment by diederikdehaas** [comment]
There is a new driver version, but that still doesn't support kernel 5.8.
As I have explained in the README, I don't plan to spend any time on it. If someone makes a (clean) PR, I can take a look.

**Comment by diederikdehaas** [comment]
Looks like https://github.com/aircrack-ng/rtl8814au does have a fix for 5.8 kernels (and later)
