### ISSUE TITLE
hostapd and DFS support?

### ISSUE THREAD

**Issue by bartgrefte** [diederikdehaas/rtl8814AU#3]
Does the RTL8814AU (in an ASUS USB-AC68) support access point mode with hostapd and maybe on DFS channels as well?

Although https://gathering.tweakers.net/forum/list_message/43826469#43826469 isn't making me optimistic when it comes to DFS, it says that all ASUS USB AC adapters do not support DFS (back in 2015 that is)...

**Comment by diederikdehaas** [comment]
I don't even know what DFS is. (And don't care; sorry; nothing personal)
