### ISSUE TITLE
issues in 4.4.0-74-generic kernel

### ISSUE THREAD

**Issue by henzeb** [diederikdehaas/rtl8814AU#4]
i've been ruining my whole evening over this, but something in kernel 4.4.0-74-generic broke this driver. thought I was having issues with wicd (because i was trying to install this after noticing network-manager was blocking my network while scanning for networks), turned out the new kernel. in dmesg I get messages like "disagrees about version of symbol cfg80211_inform_bss_frame_data"
last working kernel is 4.4.0-72-generic

**Comment by diederikdehaas** [comment]
That sounds like a problem with your kernel (headers). There is a new driver version you could try, but also the older one is supposed to work with a 4.4 kernel.
